basePath: /api/v1
consumes:
- application/json
definitions:
  Error:
    description: Error model
    properties:
      message:
        type: string
    type: object
  Health:
    description: Health model
    properties:
      healthy:
        type: boolean
    type: object
  Song:
    description: Model for creating a new song
    properties:
      author:
        type: string
      duration:
        type: string
      release:
        type: string
      title:
        type: string
    required:
    - author
    - duration
    - release
    - title
    type: object
  SongDto:
    description: Model for a created song
    properties:
      author:
        type: string
      duration:
        type: string
      id:
        type: string
      release:
        type: string
      title:
        type: string
    required:
    - author
    - duration
    - release
    - title
    type: object
  Version:
    description: Version model
    properties:
      version:
        type: string
    type: object
info:
  contact:
    name: David Slatinek
    url: https://github.com/david-slatinek
  description: API for song management
  license:
    name: Apache-2.0 license
    url: https://www.apache.org/licenses/LICENSE-2.0
  termsOfService: http://swagger.io/terms/
  title: Song API
  version: "1.0"
paths:
  /health:
    get:
      description: Perform healthcheck.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Health'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Health'
      summary: Perform healthcheck
      tags:
      - health
  /songs:
    get:
      description: Get all songs.
      produces:
      - application/json
      responses:
        "200":
          description: An array of songs
          schema:
            items:
              $ref: '#/definitions/SongDto'
            type: array
        "204":
          description: No Content
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Error'
      summary: Get all songs
      tags:
      - song
    post:
      consumes:
      - application/json
      description: Create a new song.
      parameters:
      - description: Song info
        in: body
        name: requestBody
        required: true
        schema:
          $ref: '#/definitions/Song'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/SongDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Error'
      summary: Create a new song
      tags:
      - song
  /songs/{id}:
    delete:
      description: Delete song.
      parameters:
      - description: Song ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Error'
      summary: Delete song
      tags:
      - song
    get:
      description: Get a song by id.
      parameters:
      - description: Song ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/SongDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Error'
      summary: Get a song by id
      tags:
      - song
    put:
      consumes:
      - application/json
      description: Update song.
      parameters:
      - description: Song ID
        in: path
        name: id
        required: true
        type: string
      - description: Updated song
        in: body
        name: requestBody
        required: true
        schema:
          $ref: '#/definitions/Song'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/SongDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Error'
      summary: Update song
      tags:
      - song
  /version:
    get:
      description: Get API version.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Version'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Error'
      summary: Get API version
      tags:
      - version
produces:
- application/json
schemes:
- http
swagger: "2.0"
