services:
  db:
    image: postgres:16.4-alpine3.20
    restart: unless-stopped
    hostname: minerva-db
    container_name: minerva-db
    environment:
      - POSTGRES_USER=david
      - POSTGRES_PASSWORD=david
      - POSTGRES_DB=minerva
    ports:
      - "5432:5432"
    volumes:
      - minerva-db:/var/lib/postgresql/data
      - ./create.sql:/docker-entrypoint-initdb.d/create.sql
    networks:
      - minerva
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "songs" ]
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 10s

volumes:
  minerva-db:
    name: minerva-db

networks:
  minerva:
    name: minerva
    driver: bridge
