services:
  db:
    image: postgres:16.4-alpine3.20
    restart: always
    environment:
      - POSTGRES_USER=david
      - POSTGRES_PASSWORD=david
      - POSTGRES_DB=minerva
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
      - ./create.sql:/docker-entrypoint-initdb.d/create.sql

volumes:
  data:
