services:
  db:
    image: postgres:16.4-alpine3.20
    restart: always
    hostname: minerva-db
    environment:
      - POSTGRES_USER=david
      - POSTGRES_PASSWORD=david
      - POSTGRES_DB=minerva
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
      - ./create.sql:/docker-entrypoint-initdb.d/create.sql
    networks:
      - minerva-network

volumes:
  data:

networks:
  minerva-network:
    name: minerva-network
    driver: bridge
