services:
  db:
    image: postgres:17.2-alpine3.21
    restart: unless-stopped
    container_name: cli-db
    environment:
      - POSTGRES_USER=david
      - POSTGRES_PASSWORD=david
      - POSTGRES_DB=cli
    ports:
      - "5000:5432"
    volumes:
      - cli-db:/var/lib/postgresql/data
      - ./create.sql:/docker-entrypoint-initdb.d/create.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 10s

volumes:
  cli-db:
    name: cli-db
