---
# Playbook to install required packages

- name: Install required packages
  hosts: all

  tasks:
    - name: Update
      become: true
      ansible.builtin.apt:
        autoclean: true
        autoremove: true
        cache_valid_time: 3600
        clean: true
        update_cache: true
        upgrade: "full"

    - name: Install required packages
      become: true
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - software-properties-common
        state: present
        update_cache: true

    - name: Add Docker Module Repository
      become: true
      ansible.builtin.deb822_repository:
        name: docker
        types: [ deb ]
        uris: "https://download.docker.com/linux/{{ ansible_distribution | lower }}"
        signed_by: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
        suites: [ "{{ ansible_distribution_release | lower }}" ]
        components: [ stable ]
        state: present
        enabled: true

    - name: Install Docker and related packages
      become: true
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: true

    - name: Add Docker group
      ansible.builtin.group:
        name: docker
        state: present

    - name: Add user to Docker group
      become: true
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true

    - name: Enable and start Docker services
      ansible.builtin.systemd_service:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - docker.service
        - containerd.service
