services:
  minerva-api:
    build:
      context: .
      args:
        FILE: config.docker
    container_name: minerva-api
    ports:
      - "8080:8080"
    networks:
      - minerva

networks:
  minerva:
    name: minerva
    driver: bridge
