services:
  minerva-api:
    build:
      args:
        FILE: config.docker
    container_name: minerva-api
    ports:
      - "8080:8080"
    networks:
      - minerva
    environment:
      ENABLE_LOGGING: $ENABLE_LOGGING
      VERSION: $VERSION
      NEW_RELIC_KEY: $NEW_RELIC_KEY

networks:
  minerva:
    name: minerva
    driver: bridge
    external: true
