services:
  minerva-api:
    image: {{ image }}
    container_name: minerva-api
    ports:
      - "80:8080"
    networks:
      - minerva
    environment:
      ENABLE_LOGGING: $ENABLE_LOGGING
      NEW_RELIC_KEY: $NEW_RELIC_KEY

networks:
  minerva:
    name: minerva
    driver: bridge
    external: true
