services:
  minerva-api:
    image: {{ image }}
    container_name: minerva-api
    ports:
      - "80:8080"
    networks:
      - minerva-network

networks:
  minerva-network:
    name: minerva-network
    driver: bridge
