name: Deploy API

on:
  push:
    tags: [ "v[0-9].[0-9].[0-9]" ]

jobs:
  build:
    name: Build standalone artefact
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Build
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.1"
      - run: |
          go mod download -x
          go build -v main.go

  docker:
    name: Build docker image
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: api

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          docker build -t minerva:latest --build-arg FILE=config.prod .
          docker image tag minerva:latest minerva:${{  github.ref_name }}

  push:
    name: Push to ECR
    runs-on: ubuntu-latest
    needs: docker

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "eu-central-1"

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: minerva
        run: |
          docker push minerva:latest
          docker push minerva:${{  github.ref_name }}
